### PR TITLE
Add documentation to use Github Workflow

### PR DESCRIPTION
**Pull request by Macleykun**
This pull request adds information and the Workflow to automate the process of creating AVIF and WEBP images based on changes on jpg/jpeg/png files on commit.

This workflow contains only the way how to push the changes, not pull.

I tested both ways but noticed that the pull methode can create a loop. As accepting the pull makes a new commit that isn't from a workflow user. The compression on jpg/jpeg/png seems to not be applied as these files were actually converted from compressed webp.

This pull does contain work from calibreapp/image-actions@main. I believe it adds even more functionality to the workflow as images are futher compressed which safes even more. I know optimizt has this aswell for jpg/jpeg/png but not for webp i believe. *I would like to hear if this decision is ok, otherwise i remove that part and/or edit the workflow to include the compression from optimizt.*

[Proof of commit based](https://github.com/TheVoxSiren/voxsiren.net/tree/32ecb1213173e6b6b56b8aba7a65140d6694e6dd/assets/images
)
[Proof of pull based](https://github.com/TheVoxSiren/voxsiren.net/pull/17). Note that a new file was added later (work-process-item-01.png) and this one was also added to the pull request.

A few things i would like to adres
- When i tried to install withoud sudo it obviously gave this [error](work-process-item-01.webp). But with sudo i got this [error](https://github.com/TheVoxSiren/voxsiren.net/runs/2043280708?check_suite_focus=true). I'm not sure if this is a problem but i could fix it with [`--unsafe-perm`](https://github.com/TheVoxSiren/voxsiren.net/runs/2043298394?check_suite_focus=true). Does this need fixing or is this ok?
- A problem might occure if the user removes a webp or avif file. This workflow does not check for these types of files. I think it wouldn't make sense to also check on these files because of the following two reasons:
1. The user removed the image for a reason, if they edit the png/jpg/jpeg it'll get replaced anyways.
2. If the user adds their own avif/webp image, the workflow wouldn't output anything. As optimizt doesn't convert from webp/avif to avif/webp (rightfully so).
While issue 2 doesn't seem to be much of a problem, the first issue would but it would be rather a user error rather then the faulth of the workflow. But i don't see the point of checking on changes of webp/avif.
- I will include the pull request code here, but users should not trigger this build by commit. Rather any other means will do, as that won't retrigger it.

I believe i mentioned everything that i had to mention. The workflow works great based on commit and push. It's just the pull that i can't fix. Just let me know if ya guys want the calibri part to be in or not. Idk if ya can futher compress AVIF, or if optimizt can do this. But please let me know as i love to save even more on images :).

### CODE REVIEW

**Comment by Macleykun** [comment]
Small note however, i noticed one problem that might need attention:
IF a user changes an normal image like png. And we already made a webp/avif format.
The change of the png triggers the workflow (good) but it won't replace the webp/avif as it already excists.

Is it possible to --force replacing the webp/avif file so that the latest will always be applied? Or atleast check if the replaced file is the same as the current one?

**Comment by Macleykun** [comment]
Another thing i noticed is that one file was skipped:
https://github.com/TheVoxSiren/voxsiren.net/runs/2046762218?check_suite_focus=true
donate-button
the webp variant i made with a online tool seems to be smaller, so idk why it skipped that :P ?

**Comment by Macleykun** [comment]
Moved to #13

**Comment by 343dev** [comment]
> This pull does contain work from calibreapp/image-actions@main. I believe it adds even more functionality to the workflow as images are futher compressed which safes even more. I know optimizt has this aswell for jpg/jpeg/png but not for webp i believe. I would like to hear if this decision is ok, otherwise i remove that part and/or edit the workflow to include the compression from optimizt.

Optimizt applies compression for all image types, but doesn't try to compress the image as much as possible. We provide medium compression to achieve a balance between size and image quality.

> When i tried to install withoud sudo it obviously gave this error. But with sudo i got this error. I'm not sure if this is a problem but i could fix it with --unsafe-perm. Does this need fixing or is this ok?

I see you already fix it 😉

> A problem might occure if the user removes a webp or avif file. This workflow does not check for these types of files. I think it wouldn't make sense to also check on these files because of the following two reasons:

> 1. The user removed the image for a reason, if they edit the png/jpg/jpeg it'll get replaced anyways.
> 2. If the user adds their own avif/webp image, the workflow wouldn't output anything. As optimizt doesn't convert from webp/avif to avif/webp (rightfully so).

> While issue 2 doesn't seem to be much of a problem, the first issue would but it would be rather a user error rather then the faulth of the workflow. But i don't see the point of checking on changes of webp/avif.

Seems legit.

> It's just the pull that i can't fix.

Don't worry about that. I'll fix it in the future.

> Just let me know if ya guys want the calibri part to be in or not. Idk if ya can futher compress AVIF, or if optimizt can do this. But please let me know as i love to save even more on images :).

**calibreapp** has no relation to our project, so it was the right decision to remove it from #13 .

> Small note however, i noticed one problem that might need attention:
IF a user changes an normal image like png. And we already made a webp/avif format.
The change of the png triggers the workflow (good) but it won't replace the webp/avif as it already excists.
Is it possible to --force replacing the webp/avif file so that the latest will always be applied? Or atleast check if the replaced file is the same as the current one?

At now Optimizt does not have a `--force` option, but i will implement it right away after #13 will be merged.

> Another thing i noticed is that one file was skipped:
> https://github.com/TheVoxSiren/voxsiren.net/runs/2046762218?check_suite_focus=true
> the webp variant i made with a online tool seems to be smaller, so idk why it skipped that :P ?

You can use `--verbose` option to check what's going on.
I bet it's skipped because the WebP version is larger than the original one.

Maybe we should allow user to create a file anyway with `--force` option in the future 🤔

> I believe i mentioned everything that i had to mention. The workflow works great based on commit and push.

Great job. Thanks.

**Pull request closed without merging**
